### ISSUE TITLE
Error during docker compose up

### ISSUE THREAD

**Issue by voroningraphics** [Uniswap/unichain-node#11]
![image](https://github.com/user-attachments/assets/87dae9d0-8e54-48f5-abdf-6b1a7f104feb)

**Comment by 0xPotatoofdoom** [comment]
try reinstalling the docker image. something isn't set right with the permissions. you can also try running docker with less security while testing - but this isn't recommend for long term production use. 

Open your docker-compose.yml file and add the following;

version: '3'
services:
  my-service:
    image: my-image:latest
    container_name: my-container
    security_opt:
      - label=disable  # Disables SELinux/AppArmor labels (depending on your system)
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
    command: ["/entrypoint.sh"]

**Comment by voroningraphics** [comment]
Poblem is solved.
And permission +x to shell file.
Command:  `chmod +x op-get-entrypoint.sh` in project directory
